




CREATE TABLE CATEGORIE(
    ID                    INT8  NOT NULL,
	CLASS                 VARCHAR(256) NOT NULL,
    OMSCHRIJVING          VARCHAR(256) NOT NULL,
    VERSION               INT8 NOT NULL,
    CONSTRAINT CATEGORIE_PK PRIMARY KEY (ID)
);

CREATE TABLE SUBCATEGORIE(
    ID                    INT8  NOT NULL,
	CLASS                 VARCHAR(256) NOT NULL,
    OMSCHRIJVING          VARCHAR(256) NOT NULL,
    FK_CATEGORIE          INT8 NOT NULL,
    VERSION               INT8 NOT NULL,
    CONSTRAINT SUBCATEGORIE_PK PRIMARY KEY (ID),
    CONSTRAINT SUBCATEGORIE_CATEGORIE_FK FOREIGN KEY(FK_CATEGORIE) REFERENCES CATEGORIE
);

CREATE TABLE GELDSTROOM(
    ID                    INT8  NOT NULL,
	CLASS                 VARCHAR(256) NOT NULL,
    BEDRAG                NUMERIC(8,2) NOT NULL,
    DATUM                 TIMESTAMP NOT NULL,
    FK_SUBCATEGORIE       INT8  NOT NULL,
    VERSION               INT8 NOT NULL,
    CONSTRAINT UITGAVE_PK PRIMARY KEY (ID),
    CONSTRAINT UITGAVE_SUBCATEGORIE_FK FOREIGN KEY(FK_SUBCATEGORIE) REFERENCES SUBCATEGORIE
);

CREATE TABLE PRINCIPAL(
    USERNAME              VARCHAR(255)  NOT NULL,
    PASSWORD              VARCHAR(255)  NOT NULL,
    CONSTRAINT PRINCIPAL_PK PRIMARY KEY (USERNAME)
);

CREATE TABLE ROLE(
    USERNAME              VARCHAR(255)  NOT NULL,
    USERROLE              VARCHAR(255)  NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY (USERNAME, USERROLE),
    CONSTRAINT ROLE_PRINCIPAL_FK FOREIGN KEY(USERNAME) REFERENCES PRINCIPAL
);

CREATE SEQUENCE CATEGORIE_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SUBCATEGORIE_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE GELDSTROOM_SEQ INCREMENT BY 1 START WITH 1;
